#!/bin/bash
bower install
npm install
gulp build
gulp config --env local
cordova plugin add com.ionic.keyboard # not 100% why this isn't installed properly otherwise

# Run tests
echo "Running unit tests..."
gulp test

echo ""
echo ""
if [ $? != 0 ]; then
    echo "Unit tests did not pass. Please check everything is in order."
else
    echo "Unit tests passed."
fi
echo ""


echo "Setting up git hooks..."
mkdir -p .git/hooks
rm .git/hooks/*;

echo '#!/bin/bash
gulp test;' > .git/hooks/pre-commit;
chmod +x .git/hooks/pre-commit;
echo "done."

echo "Setup completed"
echo "Run 'ionic serve' to start the server"